import {database,current,seed} from '../../../lib/edu-db';
import {env} from 'cloudflare:workers';
export const dynamic='force-dynamic';
const out=(data:any,status=200)=>Response.json(data,{status});
async function hash(password:string,salt:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);return Array.from(new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256))).map(x=>x.toString(16).padStart(2,'0')).join('');}
async function signin(user:any){const token=crypto.randomUUID()+crypto.randomUUID();await database().prepare('INSERT INTO sessions (id,user_id,expires) VALUES (?,?,?)').bind(token,user.id,Date.now()+86400000*7).run();return Response.json({user:{id:user.id,name:user.name,email:user.email,role:user.role}},{headers:{'Set-Cookie':`edu_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800; Secure`}});}
export async function GET(req:Request){try{await seed();const db=database(),user=await current(req);const courses=(await db.prepare(user?.role==='admin'?'SELECT * FROM courses ORDER BY position':'SELECT * FROM courses WHERE published=1 ORDER BY position').all()).results;const lessons=(await db.prepare(user?.role==='admin'?'SELECT * FROM lessons ORDER BY position':'SELECT lessons.* FROM lessons JOIN courses ON courses.id=lessons.course_id WHERE courses.published=1 ORDER BY lessons.position').all()).results.map((l:any)=>({...l,questions:JSON.parse(l.questions).map(({answer,explanation,...q}:any)=>q)}));const progress=user?(await db.prepare('SELECT * FROM progress WHERE user_id=?').bind(user.id).all()).results:[];let admin:any={};if(user?.role==='admin'){admin.users=(await db.prepare('SELECT id,name,email,role,status,created FROM users ORDER BY created DESC').all()).results;admin.allProgress=(await db.prepare('SELECT * FROM progress').all()).results;admin.settings=(await db.prepare("SELECT * FROM settings WHERE id!='ai_key'").all()).results;admin.hasAiKey=!!await db.prepare("SELECT id FROM settings WHERE id='ai_key'").first();admin.questions=(await db.prepare('SELECT id,questions FROM lessons').all()).results.map((l:any)=>({...l,questions:JSON.parse(l.questions)}));}const messages=user?(await db.prepare(user.role==='admin'?'SELECT messages.*,users.name FROM messages JOIN users ON messages.user_id=users.id ORDER BY messages.created DESC':'SELECT * FROM messages WHERE user_id=? ORDER BY created DESC').bind(...(user.role==='admin'?[]:[user.id])).all()).results:[];const cohorts=(await db.prepare('SELECT * FROM cohorts ORDER BY starts DESC,name').all()).results;
const memberships=user?(await db.prepare('SELECT * FROM memberships').all()).results:[];
const channels=user?(await db.prepare("SELECT channels.*,users.name,users.created AS joined,memberships.cohort_id FROM channels JOIN users ON users.id=channels.user_id LEFT JOIN memberships ON memberships.user_id=users.id WHERE users.status='active' AND (channels.shared=1 OR channels.user_id=?) ORDER BY channels.created DESC").bind(user.id).all()).results:[];
const visits=user?(await db.prepare('SELECT * FROM channel_visits WHERE user_id=?').bind(user.id).all()).results:[];
return out({user,courses,lessons,progress,messages,cohorts,memberships,channels,visits,...admin});}catch(e){console.error(e);return out({error:'교육 정보를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.'},503);}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return out({error:'요청을 확인할 수 없습니다.'},403);await seed();const db=database();if(req.headers.get('content-type')?.includes('multipart/form-data')){const u=await current(req);if(u?.role!=='admin')return out({error:'관리자 권한이 필요합니다.'},403);const f=await req.formData(),file=f.get('file') as File,id=String(f.get('lessonId')||'');if(!file||file.size>50*1024*1024||!['video/mp4','video/webm'].includes(file.type))return out({error:'50MB 이하의 MP4 또는 WebM 영상을 선택해 주세요.'},400);if(!await db.prepare('SELECT id FROM lessons WHERE id=?').bind(id).first())return out({error:'강의를 찾을 수 없습니다.'},404);const key=crypto.randomUUID();await (env as any).BUCKET.put(key,file.stream(),{httpMetadata:{contentType:file.type}});await db.prepare('UPDATE lessons SET video=? WHERE id=?').bind(`/api/media/${key}`,id).run();return out({ok:true});}const body:any=await req.json(),a=body.action;
if(a==='demo'){if(!['admin','student'].includes(body.role))return out({error:'잘못된 계정입니다.'},400);const id='demo-'+body.role;await db.prepare('INSERT OR IGNORE INTO users (id,email,name,role,status,created) VALUES (?,?,?,?,?,?)').bind(id,id+'@sellerbricks.test',body.role==='admin'?'에듀 관리자':'김셀러',body.role,'active',new Date().toISOString()).run();if(body.role==='student')await db.prepare("INSERT OR IGNORE INTO memberships (user_id,cohort_id) VALUES (?,'cohort-1')").bind(id).run();return signin(await db.prepare('SELECT * FROM users WHERE id=?').bind(id).first());}
if(a==='register'){if(!/^\S+@\S+\.\S+$/.test(body.email)||String(body.password).length<10||!body.name?.trim())return out({error:'이름, 이메일과 10자 이상의 비밀번호를 입력해 주세요.'},400);const id=crypto.randomUUID(),salt=crypto.randomUUID(),pw=salt+':'+await hash(body.password,salt);try{await db.prepare('INSERT INTO users (id,email,name,role,password,status,created) VALUES (?,?,?,?,?,?,?)').bind(id,body.email.toLowerCase().trim(),body.name.trim(),'student',pw,'pending',new Date().toISOString()).run();}catch{return out({error:'이미 등록된 이메일입니다.'},400);}return out({ok:true,message:'가입 신청이 완료되었습니다. 관리자가 셀러 자격을 확인한 후 승인하면 로그인할 수 있습니다.'});}
if(a==='login'){const u:any=await db.prepare('SELECT * FROM users WHERE email=?').bind(String(body.email).toLowerCase().trim()).first();if(!u?.password)return out({error:'이메일 또는 비밀번호를 확인해 주세요.'},401);const [salt,pw]=u.password.split(':');if(await hash(body.password,salt)!==pw)return out({error:'이메일 또는 비밀번호를 확인해 주세요.'},401);if(u.status!=='active')return out({error:'관리자 승인 대기 중이거나 이용이 중지된 계정입니다.'},403);return signin(u);}
const user=await current(req);if(!user)return out({error:'로그인이 필요합니다.'},401);
if(a==='logout'){const token=req.headers.get('cookie')?.match(/edu_session=([^;]+)/)?.[1];await db.prepare('DELETE FROM sessions WHERE id=?').bind(token||'').run();return Response.json({ok:true},{headers:{'Set-Cookie':'edu_session=; HttpOnly; SameSite=Lax; Secure; Path=/; Max-Age=0'}});}
if(a==='profile'){if(!body.name?.trim())return out({error:'이름을 입력해 주세요.'},400);await db.prepare('UPDATE users SET name=? WHERE id=?').bind(body.name.trim(),user.id).run();return out({ok:true});}
if(['progress','bookmark','note','quiz'].includes(a)){const lesson:any=await db.prepare('SELECT lessons.* FROM lessons JOIN courses ON courses.id=lessons.course_id WHERE lessons.id=? AND courses.published=1').bind(body.lessonId).first();if(!lesson)return out({error:'강의를 찾을 수 없습니다.'},404);await db.prepare('INSERT OR IGNORE INTO progress (user_id,lesson_id,updated) VALUES (?,?,?)').bind(user.id,lesson.id,new Date().toISOString()).run();const p:any=await db.prepare('SELECT * FROM progress WHERE user_id=? AND lesson_id=?').bind(user.id,lesson.id).first();if(a==='bookmark')await db.prepare('UPDATE progress SET bookmark=?,updated=? WHERE user_id=? AND lesson_id=?').bind(p.bookmark?0:1,new Date().toISOString(),user.id,lesson.id).run();if(a==='note')await db.prepare('UPDATE progress SET note=?,updated=? WHERE user_id=? AND lesson_id=?').bind(String(body.note).slice(0,10000),new Date().toISOString(),user.id,lesson.id).run();if(a==='progress'){const position=Math.max(0,Math.min(Number(body.position)||0,lesson.duration)),delta=Math.max(0,Math.min(Number(body.delta)||0,15)),watched=Math.min(lesson.duration,p.watched+delta);await db.prepare('UPDATE progress SET position=?,watched=?,complete=?,updated=? WHERE user_id=? AND lesson_id=?').bind(position,watched,watched>=lesson.duration*.9&&p.score>=80?1:0,new Date().toISOString(),user.id,lesson.id).run();}if(a==='quiz'){if(p.watched<lesson.duration*.9)return out({error:'영상의 90% 이상을 시청하면 확인 문제를 풀 수 있습니다.'},400);const qs=JSON.parse(lesson.questions),score=Math.round(qs.filter((q:any,i:number)=>q.answer===body.answers?.[i]).length/qs.length*100);await db.prepare('UPDATE progress SET score=?,complete=?,updated=? WHERE user_id=? AND lesson_id=?').bind(score,score>=80?1:0,new Date().toISOString(),user.id,lesson.id).run();return out({ok:true,score,results:qs.map((q:any,i:number)=>({correct:q.answer===body.answers?.[i],answer:q.answer,explanation:q.explanation}))});}return out({ok:true});}
if(a==='question'){if(!body.body?.trim())return out({error:'질문을 입력해 주세요.'},400);await db.prepare('INSERT INTO messages (id,user_id,lesson_id,body,created) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),user.id,body.lessonId||null,body.body.slice(0,5000),new Date().toISOString()).run();return out({ok:true});}
if(a==='channel'){const hosts:any={youtube:['youtube.com','www.youtube.com','m.youtube.com','youtu.be'],instagram:['instagram.com','www.instagram.com'],tiktok:['tiktok.com','www.tiktok.com'],x:['x.com','www.x.com','twitter.com','www.twitter.com']};let url;try{url=new URL(body.url);if(url.protocol!=='https:'||!hosts[body.platform]?.includes(url.hostname)||url.username||url.password||url.port)throw 0;}catch{return out({error:'선택한 플랫폼의 HTTPS 채널 주소를 입력해 주세요.'},400);}await db.prepare('INSERT INTO channels (user_id,platform,url,bio,shared,created) VALUES (?,?,?,?,?,?) ON CONFLICT(user_id,platform) DO UPDATE SET url=excluded.url,bio=excluded.bio,shared=excluded.shared').bind(user.id,body.platform,url.href,String(body.bio||'').slice(0,300),body.shared?1:0,new Date().toISOString()).run();return out({ok:true});}
if(a==='channel_remove'){await db.prepare('DELETE FROM channels WHERE user_id=? AND platform=?').bind(user.id,body.platform).run();return out({ok:true});}
if(a==='visit'){if(body.targetId===user.id)return out({ok:true});const ch=await db.prepare('SELECT url FROM channels WHERE user_id=? AND platform=? AND shared=1').bind(body.targetId,body.platform).first();if(!ch)return out({error:'공개된 채널을 찾을 수 없습니다.'},404);await db.prepare('INSERT OR REPLACE INTO channel_visits (user_id,target_id,platform,created) VALUES (?,?,?,?)').bind(user.id,body.targetId,body.platform,new Date().toISOString()).run();return out({ok:true});}
if(user.role!=='admin')return out({error:'관리자 권한이 필요합니다.'},403);
if(a==='cohort'){if(!body.name?.trim())return out({error:'기수명을 입력해 주세요.'},400);if(body.starts&&body.ends&&body.starts>body.ends)return out({error:'종료일은 시작일 이후로 설정해 주세요.'},400);if(!['recruiting','active','completed'].includes(body.status))return out({error:'기수 상태를 확인해 주세요.'},400);await db.prepare('INSERT INTO cohorts (id,name,starts,ends,description,status) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,starts=excluded.starts,ends=excluded.ends,description=excluded.description,status=excluded.status').bind(body.id||crypto.randomUUID(),body.name.trim(),body.starts||'',body.ends||'',body.description||'',body.status).run();}
else if(a==='assign_cohort'){if(body.cohortId&&!await db.prepare('SELECT id FROM cohorts WHERE id=?').bind(body.cohortId).first())return out({error:'기수를 찾을 수 없습니다.'},404);if(body.cohortId)await db.prepare('INSERT INTO memberships (user_id,cohort_id) VALUES (?,?) ON CONFLICT(user_id) DO UPDATE SET cohort_id=excluded.cohort_id').bind(body.userId,body.cohortId).run();else await db.prepare('DELETE FROM memberships WHERE user_id=?').bind(body.userId).run();}
else if(a==='member'){if(body.id===user.id)return out({error:'현재 관리자 계정은 변경할 수 없습니다.'},400);if(!['active','pending','suspended'].includes(body.status))return out({error:'잘못된 상태입니다.'},400);await db.prepare("UPDATE users SET status=? WHERE id=? AND role='student'").bind(body.status,body.id).run();}
else if(a==='course'){if(!body.title?.trim())return out({error:'과정명을 입력해 주세요.'},400);await db.prepare('INSERT INTO courses (id,title,description,category,image,position,published) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,description=excluded.description,category=excluded.category,image=excluded.image,position=excluded.position,published=excluded.published').bind(body.id||crypto.randomUUID(),body.title,body.description||'',body.category||'입문',Number(body.image)||1,Number(body.position)||1,body.published?1:0).run();}
else if(a==='lesson'){if(!body.title?.trim()||!body.course_id)return out({error:'과정과 영상 제목을 입력해 주세요.'},400);if(body.video&&body.video!=='/sample-intro.mp4'&&!body.video.startsWith('/api/media/')&&!/^https:\/\//.test(body.video))return out({error:'HTTPS 영상 주소를 입력해 주세요.'},400);let qs;try{qs=typeof body.questions==='string'?JSON.parse(body.questions):body.questions;if(!Array.isArray(qs)||!qs.length||qs.some((q:any)=>!q.question||!Array.isArray(q.options)||q.options.length<2||!Number.isInteger(q.answer)||q.answer<0||q.answer>=q.options.length))throw 0;}catch{return out({error:'확인 문제와 정답을 확인해 주세요.'},400);}await db.prepare('INSERT INTO lessons (id,course_id,title,summary,duration,position,video,questions,resource) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET course_id=excluded.course_id,title=excluded.title,summary=excluded.summary,duration=excluded.duration,position=excluded.position,video=excluded.video,questions=excluded.questions,resource=excluded.resource').bind(body.id||crypto.randomUUID(),body.course_id,body.title,body.summary||'',Math.max(1,Number(body.duration)||600),Number(body.position)||1,body.video||'',JSON.stringify(qs),body.resource||'').run();}
else if(a==='reply')await db.prepare('UPDATE messages SET reply=? WHERE id=?').bind(String(body.reply).slice(0,5000),body.id).run();
else if(a==='settings'){for(const id of ['ai_model','video_provider','kakao_client','naver_client'])if(body[id]!==undefined)await db.prepare('INSERT INTO settings (id,value) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value').bind(id,String(body[id]).slice(0,500)).run();if(body.ai_key)await db.prepare("INSERT INTO settings (id,value) VALUES ('ai_key',?) ON CONFLICT(id) DO UPDATE SET value=excluded.value").bind(body.ai_key).run();}
else if(a==='ai'){const key:any=await db.prepare("SELECT value FROM settings WHERE id='ai_key'").first();if(!key)return out({error:'먼저 AI 설정에서 API 키를 연결해 주세요. 연결 전에는 생성 비용이 발생하지 않습니다.'},400);const model:any=await db.prepare("SELECT value FROM settings WHERE id='ai_model'").first();const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:'Bearer '+key.value,'Content-Type':'application/json'},body:JSON.stringify({model:model?.value||'gpt-4.1-mini',input:`한국어 라이브 커머스 셀러 교육용 강의 초안을 작성하세요. 주제: ${String(body.topic).slice(0,2000)}. 3분 영상 대본, 장면 구성, 학습 목표, 객관식 확인 문제 2개와 정답 해설을 작성하세요. 사실이 불확실하면 명시하세요.`,max_output_tokens:2000})});if(!response.ok)return out({error:'AI 연결 또는 모델 설정을 확인해 주세요. 초안 생성에 실패했습니다.'},502);const data:any=await response.json();return out({ok:true,text:data.output?.flatMap((i:any)=>i.content||[]).filter((c:any)=>c.type==='output_text').map((c:any)=>c.text).join('\n')||'생성 결과가 비어 있습니다.'});}
else return out({error:'지원하지 않는 작업입니다.'},400);return out({ok:true});
}catch(e){console.error('edu request failed',e);return out({error:'저장하지 못했습니다. 입력 내용을 유지한 상태로 다시 시도해 주세요.'},500);}}
