import { sqliteTable, text, integer, real, primaryKey } from 'drizzle-orm/sqlite-core';
export const users=sqliteTable('users',{id:text('id').primaryKey(),email:text('email').notNull().unique(),name:text('name').notNull(),role:text('role').notNull(),password:text('password'),status:text('status').notNull().default('active'),created:text('created').notNull()});
export const sessions=sqliteTable('sessions',{id:text('id').primaryKey(),userId:text('user_id').notNull(),expires:integer('expires').notNull()});
export const courses=sqliteTable('courses',{id:text('id').primaryKey(),title:text('title').notNull(),description:text('description').notNull(),category:text('category').notNull(),image:integer('image').notNull(),position:integer('position').notNull(),published:integer('published').notNull().default(1)});
export const lessons=sqliteTable('lessons',{id:text('id').primaryKey(),courseId:text('course_id').notNull(),title:text('title').notNull(),summary:text('summary').notNull(),duration:integer('duration').notNull(),position:integer('position').notNull(),video:text('video').notNull().default(''),questions:text('questions').notNull(),resource:text('resource').notNull().default('')});
export const progress=sqliteTable('progress',{userId:text('user_id').notNull(),lessonId:text('lesson_id').notNull(),position:real('position').notNull().default(0),watched:real('watched').notNull().default(0),complete:integer('complete').notNull().default(0),score:integer('score'),bookmark:integer('bookmark').notNull().default(0),note:text('note').notNull().default(''),updated:text('updated').notNull()},t=>[primaryKey({columns:[t.userId,t.lessonId]})]);
export const settings=sqliteTable('settings',{id:text('id').primaryKey(),value:text('value').notNull()});
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),userId:text('user_id').notNull(),lessonId:text('lesson_id'),body:text('body').notNull(),reply:text('reply').notNull().default(''),created:text('created').notNull()});
export const cohorts=sqliteTable('cohorts',{id:text('id').primaryKey(),name:text('name').notNull(),starts:text('starts').notNull().default(''),ends:text('ends').notNull().default(''),description:text('description').notNull().default(''),status:text('status').notNull().default('recruiting')});
export const memberships=sqliteTable('memberships',{userId:text('user_id').primaryKey(),cohortId:text('cohort_id').notNull()});
export const channels=sqliteTable('channels',{userId:text('user_id').notNull(),platform:text('platform').notNull(),url:text('url').notNull(),bio:text('bio').notNull().default(''),shared:integer('shared').notNull().default(1),created:text('created').notNull()},t=>[primaryKey({columns:[t.userId,t.platform]})]);
export const channelVisits=sqliteTable('channel_visits',{userId:text('user_id').notNull(),targetId:text('target_id').notNull(),platform:text('platform').notNull(),created:text('created').notNull()},t=>[primaryKey({columns:[t.userId,t.targetId,t.platform]})]);

export const userProfiles=sqliteTable('user_profiles',{userId:text('user_id').primaryKey(),avatar:integer('avatar').notNull(),nameChanges:integer('name_changes').notNull().default(0)});
